### ISSUE TITLE
Authenticates multiple passwords

### ISSUE THREAD

**Issue by SanjayMW** [korylprince/go-ad-auth#1]
Hi

If i am logged in to application, and I change my existing password. Then after i relogin, it authenticates both the passwords(New one and the existing one). I think it holds all the Active Directory data. 
Please help with this problem.

This is my code.

--->
logger.Log(MODULENAME, logger.DEBUG, "LDAP Authentication Ready To begin...!!")

	Config1 := grepo.GetGlobalConfiguration()
	//&auth.Config{} = Config.EnvConfig.UserAuthenticationConfigParams.

	config := &auth.Config{
		Server:   Config1.EnvConfig.UserAuthenticationConfigParams.Server,//example-ad.example.com
		Port:     Config1.EnvConfig.UserAuthenticationConfigParams.Port,//389
		BaseDN:   Config1.EnvConfig.UserAuthenticationConfigParams.BaseDN, //"DC=example,DC=COM",
		Security: auth.SecurityNone,
		Debug:    Config1.EnvConfig.UserAuthenticationConfigParams.Debug, //true,
	}

	status, err := auth.Login(userName, password, "", config)
	if err != nil {
		logger.Log(MODULENAME, logger.ERROR, "Failed to Perform Authentication")
		logger.Log(MODULENAME, logger.ERROR, "Error : %s \n", err.Error())
	}
	return status

**Comment by korylprince** [comment]
This library doesn't do any caching, and, as far as I know, the LDAP library doesn't either.

If your old password is working after a reset, then it's very likely an issue with what server you're connecting to. After some brief research, it appears that AD may cache passwords under certain circumstances.

In any case, this issue definitely doesn't stem from this library.

**Comment by SanjayMW** [comment]
Yes I think you might be right. But, after when i relogin it accepts the old password for a time interval of 5 mins. After that it authenticates with the new password and not with the old password. Can you help me to resolve this problem of five minutes?

**Comment by korylprince** [comment]
You might try reading this: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc755473(v=ws.10)

Beyond that, you need to look at a support site focused on Active Directory (Technet, Server Fault, etc)
