### ISSUE TITLE
Unable to change user password if TLS is not enabled in domain

### ISSUE THREAD

**Issue by dpronyaev** [korylprince/go-ad-auth#11]
```
func ExampleUpdatePassword() {
	config := &auth.Config{
		Server:   "ldap.example.com",
		Port:     389,
		BaseDN:   "OU=Users,DC=example,DC=com",
		Security: auth.SecurityNone,
	}

	username := "user"
	password := "pass"
	newPassword := "Super$ecret"

	if err := auth.UpdatePassword(config, username, password, newPassword); err != nil {
		//handle err
	}
}
```

Result is
` LDAP Result Code 53 "Unwilling To Perform": 00002077: SvcErr: DSID-03190EBE, problem 5003 (WILL_NOT_PERFORM)`

**Comment by korylprince** [comment]
Active Directory requires a secure connection to change passwords, e.g. One of `SecurityTLS`, `SecurityStartTLS`, `SecurityInsecureTLS`, `SecurityInsecureStartTLS`, though the last two are discouraged unless absolutely necessary.

I've added a hint to the example explaining such in v3.1.2.

**Comment by dpronyaev** [comment]
`Security: auth.SecurityNone,`
Unable to modify password: LDAP Result Code 53 "Unwilling To Perform": 00002077: SvcErr: DSID-03190EBE, problem 5003 (WILL_NOT_PERFORM), data 0

`Security: auth.SecurityTLS,`
Connection error: LDAP Result Code 200 "Network Error": read tcp 172.22.57.94:35218->192.168.71.17:389: read: connection reset by peer

`Security: auth.SecurityStartTLS,`
Connection error: LDAP Result Code 52 "Unavailable": 00000000: LdapErr: DSID-0C0912C4, comment: Error initializing SSL/TLS, data 0, v3839

`Security: auth.SecurityInsecureTLS,`
Connection error: LDAP Result Code 200 "Network Error": read tcp 172.22.57.94:35230->192.168.71.17:389: read: connection reset by peer

`Security: SecurityInsecureStartTLS,`
Connection error: LDAP Result Code 52 "Unavailable": 00000000: LdapErr: DSID-0C0912C4, comment: Error initializing SSL/TLS, data 0, v3839

No one of methods worked for me.

**Comment by korylprince** [comment]
Those errors indicate that you don't have TLS set up for Active Directory. If you want to change passwords, you'll at least need to add a self-signed certificate and use an `auth.SecurityInsecure*` method. Obviously a legitimate certificate (from say, Let's Encrypt) is better because it protects you from man in the middle attacks.

This may be of some help: https://serverfault.com/questions/508853/how-to-setup-ssl-for-active-directory
