### ISSUE TITLE
Wrong keyword

### ISSUE THREAD

**Issue by queuem** [korylprince/go-ad-auth#2]
In AuthenticateExtended when searching the memberOf attribute for matching groups, I think you meant to break out of the inner loop when you detect a match rather than continue.

https://github.com/korylprince/go-ad-auth/blob/c2c31824915673f6cc9e558056ab9baaa8723dc5/auth.go#L76

Continuing doesn't hurt,  but it also doesn't do anything useful :-)

**Comment by korylprince** [comment]
Thanks for catching that! I think I refactored that from earlier code that didn't have an inner loop, and missed changing it. It's fixed in v2.1.1 (2c1a6d8ba1d783acf3b062355e8f4b075686810f).
