### ISSUE TITLE
LDAP Error : Amount Of Entries Returned was not one.

### ISSUE THREAD

**Issue by SanjayMW** [korylprince/go-ad-auth#5]
Hey there,

I am trying to authenticate a particular user. But, the error message shows "Amount Of Entries Returned was not one." All other users in the same domain are able to log in,but not this user.
This user's name is 17characters long. Does this have any dependency on length of characters?
Please help me with this issue.

Thanks

**Comment by korylprince** [comment]
Can you please provide me with some example code that creates the error?

**Comment by SanjayMW** [comment]
Hi 
Here I am providing the username and password.
Code ---->

func Login(username, password, group string, config *Config) (bool, error) {
	ok, _, err := LoginWithAttrs(username, password, group, config, nil)
	return ok, err
}

/*
LoginWithAttrs will function exectly like Login, but will return a given
list of attributes for the user if login is successful.
*/
func LoginWithAttrs(username, password, group string, config *Config, attrs []string) (bool, map[string][]string, error) {
	if password == "" {
		return false, nil, nil
	}
	conn, err := config.Connect()
	if err != nil {
		return false, nil, err
	}
	defer conn.Close()

	domain, err := getDomain(config.BaseDN)
	if err != nil {
		return false, nil, err
	}

	var upn string
	if _, err = mail.ParseAddress(username); err == nil {
		upn = username
	} else {
		upn = fmt.Sprintf("%s@%s", username, domain)
	}

	lErr := conn.Bind(upn, password)
	if lErr != nil {
		if config.Debug {
			log.Printf("DEBUG: LDAP Error %v\n", lErr)
		}
		if e, ok := lErr.(*ldap.Error); ok {
			if e.ResultCode == ldap.LDAPResultInvalidCredentials {
				return false, nil, nil
			}
		}
		return false, nil, lErr
	}
	if group != "" {
		return inGroup(upn, group, config, conn, attrs)
	}
	entryAttrs, err := getAttrs(upn, config, conn, attrs)

	fmt.Println(upn, " ", config, " ", conn, " ", attrs)
	if err != nil {
		return false, nil, err
	}
	return true, entryAttrs, nil
}

In fetching the entry attributes. This error occurs.

**Comment by korylprince** [comment]
It looks like you're trying to use the v1 version of the library which is deprecated, not going to be updated, and not well tested.

Can you please try using the v2 version of the library? It's completely rewritten and fully tested. I think there's a good chance that whatever bug you've hit in v1 is likely fixed already in v2. If not, it will be much easier to find in v2.

It's not a drop-in replacement, but it's pretty easy [swap everything over](https://github.com/korylprince/go-ad-auth#new-api).

**Comment by korylprince** [comment]
Closing due to no response. Feel free to reopen if you're still having this issue.

**Comment by SanjayMW** [comment]
Hey this worked..thanks @korylprince .
