### ISSUE TITLE
ObjectGroups

### ISSUE THREAD

**Issue by zorion79** [korylprince/go-ad-auth#9]
Hello!
I could not understand which parameters i should sent.
User dn and his exist group dn?
```("dn", "user dn", []string{"group dn"})```
This is return empty groups.

**Comment by korylprince** [comment]
Yes, I think you have the right idea. `ObjectGroups` can match on any attribute including the DN. For example you could match on the `mail` attribute: 
```golang
groups, err := conn.ObjectGroups("mail", "korylprince@example.com", []string{"CN=Example Group,OU=Groups,DC=example,DC=com"})
if err != nil {
    //handle err
}
fmt.Println(groups)

//assuming user is in the group
//output:
//[CN=Example Group,OU=Groups,DC=example,DC=com]
```

You can use the attr `dn` and the user DN as the value as well:

```golang
groups, err := conn.ObjectGroups("dn", "CN=Kory Prince,OU=Accounts,DC=example,DC=com", []string{"CN=Example Group,OU=Groups,DC=example,DC=com"})
```
If you're not getting any groups returned then either:

* The user is not in the group or nested group (nested groups requires at least v3.1.0)
* The group does not exist under your `Config.BaseDN`

My guess is probably the second one.
